### PR TITLE
Prove's testsuite was fixed and now it can run a self-test in Travis.

### PR DESCRIPTION
**Pull request by svetlyak40wt**
Also, for some reason, when running on Travis, tests failed
with message: The name "ASDF" does not designate any package.
This error was fixed too.

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
@fukamachi I need help here. Tests work in SBCL, CCL, ABCL and ECL, but fail for Clisp, because:
```
$ ros +Q -l prove-asdf.asd -e '(asdf:load-system :prove-asdf)'
*** - LOAD: A file with name ASDF does not exist
The following restarts are available:
SKIP           :R1      skip (REQUIRE 'ASDF)
RETRY          :R2      retry (REQUIRE 'ASDF)
STOP           :R3      stop loading file /home/travis/build/fukamachi/prove/prove-asdf.asd
SKIP           :R4      skip (UNLESS # # ...)
RETRY          :R5      retry (UNLESS # # ...)
STOP           :R6      stop loading file /home/travis/.roswell/lisp/init.lisp
Break 1 [3]> 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

And in Allegro and CMUCL because of same problem:
```
ros -e '(format t "~&~A ~A up and running! (ASDF ~A)~2%"
                (lisp-implementation-type)
                (lisp-implementation-version)
                #+asdf(asdf:asdf-version) #-asdf "not required")' || exit 1
# Setup ASDF source regisry
ASDF_SR_CONF_DIR="$HOME/.config/common-lisp/source-registry.conf.d"
ASDF_SR_CONF_FILE="$ASDF_SR_CONF_DIR/ci.conf"
LOCAL_LISP_TREE="$HOME/lisp"
mkdir -p "$ASDF_SR_CONF_DIR"
mkdir -p "$LOCAL_LISP_TREE"
if [ "$TRAVIS" ]; then
    echo "(:tree \"$TRAVIS_BUILD_DIR/\")" > "$ASDF_SR_CONF_FILE"
elif [ "$CIRCLECI" ]; then
    echo "(:tree \"$HOME/$CIRCLE_PROJECT_REPONAME/\")" > "$ASDF_SR_CONF_FILE"
fi
echo "(:tree \"$LOCAL_LISP_TREE/\")" >> "$ASDF_SR_CONF_FILE"
Selecting previously unselected package libc6-i386.
(Reading database ... 98849 files and directories currently installed.)
Preparing to unpack .../libc6-i386_2.19-0ubuntu6.9_amd64.deb ...
Unpacking libc6-i386 (2.19-0ubuntu6.9) ...
Setting up libc6-i386 (2.19-0ubuntu6.9) ...
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
Installing allegro...
sh: 167: Syntax error: end of file unexpected (expecting "fi")
The command "curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh" failed and exited with 2 during .
```

Could you help me here?

**Comment by fukamachi** [comment]
I suppose Roswell's CI testing is unstable for those implementations.
It's okay with allow_failures for now.

CC @snmsts

**Comment by svetlyak40wt** [comment]
Ok, I'm experimenting with different settings, but seems CLISP just doesn't see ASDF3, installed by Roswell.

**Comment by snmsts** [comment]
use 'ros -A'

**Comment by svetlyak40wt** [comment]
@snmsts it helped a little, but clisp anyway brokes at:
```
$ ros -e '(ql:quickload :prove) (uiop:quit (if (prove:run-test-system :prove-test) 0 1))'
To load "prove":
  Load 1 ASDF system:
    prove
; Loading "prove"
WARNING: The generic function #<STANDARD-GENERIC-FUNCTION PERFORM> is being
         modified, but has already been called.
WARNING: Replacing method
          #<STANDARD-METHOD
            (#<STANDARD-CLASS COMPILE-OP> #<STANDARD-CLASS TEST-FILE>)>
         in #<STANDARD-GENERIC-FUNCTION PERFORM>
WARNING: Replacing method
          #<STANDARD-METHOD
            (#<STANDARD-CLASS LOAD-OP> #<STANDARD-CLASS TEST-FILE>)>
         in #<STANDARD-GENERIC-FUNCTION PERFORM>
WARNING: The generic function #<STANDARD-GENERIC-FUNCTION PERFORM> is being
         modified, but has already been called.
To load "prove-test":
  Load 1 ASDF system:
    prove-test
; Loading "prove-test"
[package split-sequence]..........................
[package prove.t.utils]
Running a test file '/home/travis/build/fukamachi/prove/t/prove.lisp'
*** - NO-APPLICABLE-METHOD: When calling
      #<STANDARD-GENERIC-FUNCTION ASDF:PERFORM> with arguments
      (ASDF:LOAD-SOURCE-OP #<PROVE.ASDF:TEST-FILE "prove-test" "t" "prove">),
      no method is applicable.
The following restarts are available:
RETRY          :R1      try calling ASDF:PERFORM again
RETURN         :R2      specify return values
SKIP-TEST-FILE :R3      Skip this test file.
SKIP-ALL-TEST-FILES :R4 Give up all test files.
SKIP           :R5      skip (UNLESS # # ...)
RETRY          :R6      retry (UNLESS # # ...)
STOP           :R7      stop loading file /home/travis/.roswell/lisp/init.lisp
Break 1 [3]> 
```

Do you have any ideas, why?

And `-A` broke build on SBCL:
```
$ ros +Q -A -e '(require "asdf")' -l prove-asdf.asd -e '(asdf:load-system :prove-asdf)'
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1001BBF563}>:
  asdf download error?
Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Ignore runtime option --eval "(ros:run '((:eval\"(ros:asdf)\")(:eval \"(require \\\"asdf\\\")\")(:load \"prove-asdf.asd\")(:eval \"(asdf:load-system :prove-asdf)\")(:quit)))".
  1: [ABORT   ] Skip rest of --eval and --load options.
  2:            Skip to toplevel READ/EVAL/PRINT loop.
  3: [EXIT    ] Exit SBCL (calling #'EXIT, killing the process).
(ROSWELL:ASDF :NO-DOWNLOAD NIL)
0] 
```

Why?

**Comment by svetlyak40wt** [comment]
@fukamachi I've done with this pull-request. It still fails on clisp, but please, review it and merge if it is good.

**Comment by svetlyak40wt** [comment]
@fukamachi Eitaro? :)

**Comment by fukamachi** [comment]
Great. Thanks!

**Pull request merged**
